-- 0036_publication_provenance_bridge
-- Ticket 08: publication backend foundation — final-course-content eligibility
-- and the course-item provenance semantic bridge.
--
-- Problem being solved:
--   draft_course_items.content_review_reference currently points to a *manual*
--   audit event (admin.course.item.create) generated by the manual item path.
--   That is Path A (manual item).  There is no way to express Path B: a course
--   item whose course-specific Chinese meaning comes from an *accepted review
--   decision* (Ticket 07).  This migration adds the distinguishing identity so that
--   publication eligibility can trace a Path-B item back to a real review_decision
--   and its immutable snapshot (source / revision / license / attribution), while
--   fully preserving the legal manual Path A.
--
-- Design:
--   - provenance_kind: 'manual' | 'review' — the item's provenance class.
--   - review_decision_id: nullable FK -> review_decisions (RESTRICT).  Non-null
--     ONLY for Path B (provenance_kind = 'review').  When set, the item's meaning
--     is understood to derive from review_decision_snapshots, and publication
--     requires the decision to be accepted / accepted_with_edits with complete
--     provenance (enforced at the application layer; the FK keeps it traceable).
--   - content_review_reference is KEPT (NOT NULL, FK audit_events) for Path A;
--     for Path B it records the *absorption* audit event.  The two columns together
--     give distinguishable logical identities without breaking the existing manual
--     path and without renaming or dropping the legacy reference column.
--
-- Immutability: released_course_items already carries immutability triggers (0007);
-- we add review_decision_id there as a frozen snapshot trace.  No UPDATE/DELETE
-- bypass is introduced.  FKs are RESTRICT (never CASCADE away a review decision /
-- a publication basis).  No session_replication_role / DISABLE TRIGGER.

-- ---- draft_course_items: provenance identity ----
ALTER TABLE draft_course_items
  ADD COLUMN provenance_kind text NOT NULL DEFAULT 'manual'
      CHECK (provenance_kind IN ('manual', 'review')),
  ADD COLUMN review_decision_id uuid REFERENCES review_decisions (id) ON DELETE RESTRICT;

-- 一致性 guard：review_decision_id 非空 ⟺ provenance_kind = 'review'。
-- 若 provenance_kind='review' 但无 review_decision_id，属伪造 accepted provenance，拒绝。
ALTER TABLE draft_course_items
  ADD CONSTRAINT draft_course_items_provenance_consistency_check
  CHECK (
    (provenance_kind = 'review' AND review_decision_id IS NOT NULL)
    OR (provenance_kind = 'manual' AND review_decision_id IS NULL)
  );

CREATE INDEX draft_course_items_review_decision_idx
  ON draft_course_items (review_decision_id) WHERE review_decision_id IS NOT NULL;

-- ---- released_course_items: frozen provenance snapshot trace ----
ALTER TABLE released_course_items
  ADD COLUMN provenance_kind text NOT NULL DEFAULT 'manual'
      CHECK (provenance_kind IN ('manual', 'review')),
  ADD COLUMN review_decision_id uuid REFERENCES review_decisions (id) ON DELETE RESTRICT;

ALTER TABLE released_course_items
  ADD CONSTRAINT released_course_items_provenance_consistency_check
  CHECK (
    (provenance_kind = 'review' AND review_decision_id IS NOT NULL)
    OR (provenance_kind = 'manual' AND review_decision_id IS NULL)
  );

CREATE INDEX released_course_items_review_decision_idx
  ON released_course_items (review_decision_id) WHERE review_decision_id IS NOT NULL;