/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["HealthController_live"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["HealthController_ready"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 登录并建立会话 cookie */
    post: operations["AuthController_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 当前账号 */
    get: operations["AuthController_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 撤销当前会话并清除 cookie */
    post: operations["AuthController_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 修改当前/首次密码并撤销其他会话 */
    post: operations["AuthController_changePassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出当前用户会话摘要 */
    get: operations["AuthController_sessions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/sessions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 撤销一条自有会话 */
    delete: operations["AuthController_revokeSession"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出账号 */
    get: operations["AdminUsersController_list"];
    put?: never;
    /** 创建受邀账号，返回一次性密码（仅此一次） */
    post: operations["AdminUsersController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查看账号安全字段 */
    get: operations["AdminUsersController_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{id}/disable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 停用账号并撤销其全部会话 */
    post: operations["AdminUsersController_disable"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{id}/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 重置一次性密码并撤销全部会话 */
    post: operations["AdminUsersController_reset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/lexical-entries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 搜索/分页词条（规范化拼写、来源状态、引用次数、更新时间） */
    get: operations["LexicalEntryController_list"];
    put?: never;
    /** 创建手工词条；重复候选返回 409 及候选，不静默落库 */
    post: operations["LexicalEntryController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/lexical-entries/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 词条事实与来源摘要 */
    get: operations["LexicalEntryController_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/courses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 课程列表（草稿版本、可见状态） */
    get: operations["CourseController_list"];
    put?: never;
    /** 创建稳定课程并同时创建初始草稿（draftVersion=1） */
    post: operations["CourseController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/draft": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 草稿详情：元数据、版本与有序单元 */
    get: operations["CourseController_getDraft"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 更新草稿元数据（If-Match 或 draftVersion） */
    patch: operations["CourseController_updateDraft"];
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 校验草稿：只读、不创建 release、不改变 current-release */
    post: operations["CourseController_validate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/draft/units/{unitId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 新增单元（客户端分配稳定 unitId，追加到末尾） */
    post: operations["CourseController_createUnit"];
    /** 删除单元并重排 */
    delete: operations["CourseController_deleteUnit"];
    options?: never;
    head?: never;
    /** 编辑单元标题/描述 */
    patch: operations["CourseController_updateUnit"];
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/draft/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 提交完整单元顺序并事务重排 */
    post: operations["CourseController_reorder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/draft/items/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 提交单元内完整词项顺序并事务重排 */
    post: operations["CourseController_reorderItems"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/draft/items/{itemId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 新增课程词项（客户端分配稳定 course_item_id） */
    post: operations["CourseController_createItem"];
    /** 删除课程词项并重排 */
    delete: operations["CourseController_deleteItem"];
    options?: never;
    head?: never;
    /** 编辑课程词项（释义/提示/移动到其他单元） */
    patch: operations["CourseController_updateItem"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginDto: {
      /** @description 登录用户名 */
      username: string;
      /** @description 密码 */
      password: string;
    };
    ChangePasswordDto: {
      /** @description 当前密码（或一次性密码） */
      currentPassword: string;
      /** @description 新密码 */
      newPassword: string;
    };
    CreateUserDto: {
      /** @description 登录用户名（小写） */
      username: string;
      /** @description 显示名 */
      displayName: string;
      /** @description IANA 时区 */
      timezone: string;
      /** @description 每日时间预算（分钟） */
      dailyBudgetMinutes: number;
      /**
       * @default learner
       * @enum {string}
       */
      role: "learner" | "admin";
    };
    LexicalEntrySummaryDto: {
      /** @description 词条 ID */
      id: string;
      /** @description 规范展示拼写 */
      canonicalSpelling: string;
      /** @description 查询/去重用规范化拼写 */
      normalizedSpelling: string;
      /** @description 词性（可空） */
      partOfSpeech: string | null;
      /** @description 来源状态（当前权威来源类型） */
      sourceStatus: string;
      /** @description 课程词项引用次数；课程词项工单落地前恒为 0（预留 lexicalEntryId 查询边界） */
      referenceCount: number;
      /** @description 最近更新时间 */
      updatedAt: string;
    };
    PageInfoDto: {
      /** @description 下一页游标；无更多时 null */
      cursor: string | null;
      /** @description 是否还有更多 */
      hasMore: boolean;
    };
    LexicalEntryListResponseDto: {
      items: components["schemas"]["LexicalEntrySummaryDto"][];
      page: components["schemas"]["PageInfoDto"];
    };
    SenseDto: {
      /** @description 中文释义 */
      meaning: string;
      /** @description 例句 */
      example?: string;
    };
    CreateLexicalEntryDto: {
      /** @description 规范展示拼写（保留原样，不因小写无条件合并同形异义词） */
      canonicalSpelling: string;
      /**
       * @description 词性
       * @enum {string}
       */
      partOfSpeech?:
        | "noun"
        | "verb"
        | "adjective"
        | "adverb"
        | "pronoun"
        | "preposition"
        | "conjunction"
        | "interjection"
        | "determiner"
        | "article"
        | "numeral"
        | "particle"
        | "phrase"
        | "abbreviation"
        | "prefix"
        | "suffix";
      /** @description 发音标注 */
      pronunciation?: string;
      /** @description 结构化释义 */
      senses?: components["schemas"]["SenseDto"][];
      /** @description 来源说明（不进入审计摘要） */
      sourceNote?: string;
      /**
       * @description 确认允许创建同形异义词条（重复候选提示后）
       * @default false
       */
      confirmDuplicate: boolean;
    };
    ProvenanceDto: {
      /** @description 来源类型 */
      sourceType: string;
      /** @description 来源说明 */
      sourceNote: string | null;
      /** @description 来源内容哈希 */
      contentHash: string;
      /** @description 创建者用户名 */
      createdByUsername: string | null;
      /** @description 来源记录时间 */
      createdAt: string;
    };
    AuditSummaryDto: {
      /** @description 审计动作 */
      action: string;
      /** @description 发生时间 */
      createdAt: string;
    };
    LexicalEntryDetailDto: {
      id: string;
      canonicalSpelling: string;
      normalizedSpelling: string;
      partOfSpeech: string | null;
      pronunciation: string | null;
      /** @description 结构化释义 */
      senses: components["schemas"]["SenseDto"][];
      /** @description 词条状态 */
      status: string;
      /** @description 来源状态（当前权威来源类型） */
      sourceStatus: string;
      /** @description 课程词项引用次数（课程词项落地前恒为 0） */
      referenceCount: number;
      createdAt: string;
      updatedAt: string;
      provenance: components["schemas"]["ProvenanceDto"][];
      /** @description 最近 10 条针对该词条的审计操作 */
      recentOperations: components["schemas"]["AuditSummaryDto"][];
    };
    DuplicateCandidateDto: {
      id: string;
      canonicalSpelling: string;
      normalizedSpelling: string;
    };
    DuplicateWarningErrorDto: {
      /** @description 错误码：DUPLICATE_WARNING 或 DUPLICATE_ENTRY */
      code: string;
      message: string;
      requestId: string;
      /** @description 重复候选词条 */
      duplicateCandidates: components["schemas"]["DuplicateCandidateDto"][];
      /** @description 是否可重试 */
      retryable: boolean;
    };
    DuplicateErrorEnvelopeDto: {
      error: components["schemas"]["DuplicateWarningErrorDto"];
    };
    CourseListItemDto: {
      id: string;
      /** @description 课程 slug（唯一） */
      slug: string;
      /** @description 当前标题（来自 active 草稿） */
      title: string;
      level: string;
      /** @description 当前描述（来自 active 草稿） */
      description: string | null;
      /** @description 课程可见性 */
      visibility: string;
      /** @description 课程状态 */
      status: string;
      /** @description active 草稿 ID */
      draftId: string | null;
      /** @description active 草稿版本 */
      draftVersion: number | null;
      /** @description 最近编辑时间（来自 active 草稿） */
      updatedAt: string;
    };
    CourseListResponseDto: {
      items: components["schemas"]["CourseListItemDto"][];
    };
    CreateCourseDto: {
      /** @description 课程 slug（唯一，小写字母/数字/连字符） */
      slug: string;
      /** @description 课程标题 */
      title: string;
      /**
       * @description 级别
       * @default a1
       * @enum {string}
       */
      level: "a1" | "a2" | "b1" | "b2" | "c1" | "c2";
      /** @description 课程描述 */
      description?: string;
    };
    CreateCourseResultDto: {
      courseId: string;
      draftId: string;
      /** @description 初始草稿版本 */
      draftVersion: number;
      slug: string;
      title: string;
      level: string;
    };
    DraftItemSummaryDto: {
      /** @description 全局词条 ID */
      id: string;
      /** @description 英语拼写 */
      canonicalSpelling: string;
      /** @description 规范化拼写 */
      normalizedSpelling: string;
      /** @description 词条来源状态 */
      sourceStatus: string;
    };
    ItemDto: {
      /** @description 稳定 course_item_id */
      id: string;
      /** @description 单元内 1 起始的位置 */
      position: number;
      /** @description 课程专属中文释义 */
      meaning: string;
      /** @description 可选提示 */
      hint: string | null;
      /** @description 人工内容 provenance：关联的管理员审计事件 ID */
      contentReviewReference: string;
      /** @description 引用的全局词条摘要 */
      lexicalEntry: components["schemas"]["DraftItemSummaryDto"];
      createdAt: string;
      updatedAt: string;
    };
    UnitDto: {
      /** @description 稳定 unit_id */
      id: string;
      /** @description 1 起始的位置 */
      position: number;
      title: string;
      description: string | null;
      /** @description 按 position 升序的课程词项 */
      items: components["schemas"]["ItemDto"][];
      createdAt: string;
      updatedAt: string;
    };
    CourseDraftDetailDto: {
      courseId: string;
      draftId: string;
      /** @description 课程 slug（唯一） */
      slug: string;
      title: string;
      level: string;
      description: string | null;
      /** @description 当前草稿版本 */
      version: number;
      status: string;
      /** @description 按 position 升序的单元大纲 */
      units: components["schemas"]["UnitDto"][];
    };
    ValidationIssueDto: {
      /** @description 稳定错误码 */
      code: string;
      /** @description 定位路径：course、unit.<unitId>、item.<itemId>.<field> */
      path: string;
      message: string;
      /**
       * @description error 阻断发布，warning 仅提示
       * @enum {string}
       */
      severity: "error" | "warning";
    };
    DiffSummaryDto: {
      /**
       * @description 首次发布或相对当前版本的差异
       * @enum {string}
       */
      kind: "initial" | "changed";
      addedUnits: number;
      removedUnits: number;
      addedItems: number;
      removedItems: number;
      changedItems: number;
      totalUnits: number;
      totalItems: number;
    };
    CourseValidationResultDto: {
      /** @description 被校验草稿的版本 */
      draftVersion: number;
      /** @description 是否存在阻断错误 */
      isPublishable: boolean;
      /** @description 阻断发布的问题 */
      blockingErrors: components["schemas"]["ValidationIssueDto"][];
      /** @description 提示但可发布的问题 */
      warnings: components["schemas"]["ValidationIssueDto"][];
      diffSummary: components["schemas"]["DiffSummaryDto"];
      /** @description 受影响学习者数量；第 4 阶段无报名数据时为 0 */
      affectedLearnerCount: number;
      /** @description 校验时刻（RFC 3339 UTC） */
      validatedAt: string;
      /** @description 草稿内容规范化序列化 SHA-256 */
      contentHash: string;
      /** @description 校验令牌：draftVersion.contentHash 前缀，发布须携带精确版本 */
      validationToken: string;
    };
    UpdateCourseDraftDto: {
      /** @description 课程 slug（唯一，小写字母/数字/连字符） */
      slug?: string;
      /** @description 课程标题 */
      title?: string;
      /**
       * @description 级别
       * @enum {string}
       */
      level?: "a1" | "a2" | "b1" | "b2" | "c1" | "c2";
      /** @description 课程描述 */
      description?: string;
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    DraftVersionConflictErrorDto: {
      /** @description 错误码：DRAFT_VERSION_CONFLICT */
      code: string;
      message: string;
      requestId: string;
      /** @description 服务端当前草稿版本 */
      currentDraftVersion: number;
      /** @description 是否可重试 */
      retryable: boolean;
    };
    DraftVersionConflictEnvelopeDto: {
      error: components["schemas"]["DraftVersionConflictErrorDto"];
    };
    CreateUnitDto: {
      /** @description 单元标题 */
      title: string;
      /** @description 单元描述 */
      description?: string;
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    UpdateUnitDto: {
      /** @description 单元标题 */
      title?: string;
      /** @description 单元描述 */
      description?: string;
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    DeleteUnitDto: {
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    ReorderUnitsDto: {
      /** @description 完整单元 ID 顺序（无重复、无遗漏） */
      unitIds: string[];
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    ReorderItemsDto: {
      /** @description 所属草稿单元 ID */
      unitId: string;
      /** @description 该单元内完整词项 ID 顺序（无重复、无遗漏、无陌生 ID） */
      itemIds: string[];
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    CreateItemDto: {
      /** @description 所属草稿单元 ID */
      unitId: string;
      /** @description 引用的全局词条 ID */
      lexicalEntryId: string;
      /** @description 课程专属中文释义（必填） */
      meaning: string;
      /** @description 可选提示 */
      hint?: string;
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    UpdateItemDto: {
      /** @description 课程专属中文释义（必填） */
      meaning?: string;
      /** @description 可选提示 */
      hint?: string;
      /** @description 移动到其他草稿单元（追加到该单元末尾） */
      unitId?: string;
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    DeleteItemDto: {
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_live: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_sessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_revokeSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminUsersController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminUsersController_create: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminUsersController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminUsersController_disable: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminUsersController_reset: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LexicalEntryController_list: {
    parameters: {
      query?: {
        /** @description 按规范化/展示拼写搜索 */
        q?: string;
        /** @description 键集分页游标（上次响应返回） */
        cursor?: string;
        /** @description 每页数量 */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LexicalEntryListResponseDto"];
        };
      };
    };
  };
  LexicalEntryController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateLexicalEntryDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LexicalEntryDetailDto"];
        };
      };
      /** @description 重复警告/完全相同冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DuplicateErrorEnvelopeDto"];
        };
      };
    };
  };
  LexicalEntryController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LexicalEntryDetailDto"];
        };
      };
    };
  };
  CourseController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseListResponseDto"];
        };
      };
    };
  };
  CourseController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCourseDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateCourseResultDto"];
        };
      };
      /** @description slug 已存在 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CourseController_getDraft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
    };
  };
  CourseController_updateDraft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCourseDraftDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_validate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseValidationResultDto"];
        };
      };
    };
  };
  CourseController_createUnit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        unitId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUnitDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_deleteUnit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        unitId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteUnitDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_updateUnit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        unitId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUnitDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_reorder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderUnitsDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_reorderItems: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderItemsDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_createItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateItemDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_deleteItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteItemDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_updateItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateItemDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
}
