/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["HealthController_live"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["HealthController_ready"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 登录并建立会话 cookie */
    post: operations["AuthController_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 当前账号 */
    get: operations["AuthController_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 撤销当前会话并清除 cookie */
    post: operations["AuthController_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 修改当前/首次密码并撤销其他会话 */
    post: operations["AuthController_changePassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出当前用户会话摘要 */
    get: operations["AuthController_sessions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/sessions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 撤销一条自有会话 */
    delete: operations["AuthController_revokeSession"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出账号 */
    get: operations["AdminUsersController_list"];
    put?: never;
    /** 创建受邀账号，返回一次性密码（仅此一次） */
    post: operations["AdminUsersController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查看账号安全字段 */
    get: operations["AdminUsersController_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{id}/disable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 停用账号并撤销其全部会话 */
    post: operations["AdminUsersController_disable"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{id}/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 重置一次性密码并撤销全部会话 */
    post: operations["AdminUsersController_reset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/lexical-entries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 搜索/分页词条（规范化拼写、来源状态、引用次数、更新时间） */
    get: operations["LexicalEntryController_list"];
    put?: never;
    /** 创建手工词条；重复候选返回 409 及候选，不静默落库 */
    post: operations["LexicalEntryController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/lexical-entries/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 词条事实与来源摘要 */
    get: operations["LexicalEntryController_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/courses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 课程列表（草稿版本、可见状态） */
    get: operations["CourseController_list"];
    put?: never;
    /** 创建稳定课程并同时创建初始草稿（draftVersion=1） */
    post: operations["CourseController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/draft": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 草稿详情：元数据、版本与有序单元 */
    get: operations["CourseController_getDraft"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 更新草稿元数据（If-Match 或 draftVersion） */
    patch: operations["CourseController_updateDraft"];
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 校验草稿：只读、不创建 release、不改变 current-release */
    post: operations["CourseController_validate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/releases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 版本历史与当前版本标记（只读） */
    get: operations["CourseController_releases"];
    put?: never;
    /** 发布不可变版本（需 Idempotency-Key；幂等重试返回原结果） */
    post: operations["CourseController_publish"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/current-release": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** 把当前版本指针指向已有 release（仅同一课程，不修改快照） */
    put: operations["CourseController_setCurrentRelease"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/draft/units/{unitId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 新增单元（客户端分配稳定 unitId，追加到末尾） */
    post: operations["CourseController_createUnit"];
    /** 删除单元并重排 */
    delete: operations["CourseController_deleteUnit"];
    options?: never;
    head?: never;
    /** 编辑单元标题/描述 */
    patch: operations["CourseController_updateUnit"];
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/draft/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 提交完整单元顺序并事务重排 */
    post: operations["CourseController_reorder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/draft/items/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 提交单元内完整词项顺序并事务重排 */
    post: operations["CourseController_reorderItems"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/courses/{id}/draft/items/{itemId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 新增课程词项（客户端分配稳定 course_item_id） */
    post: operations["CourseController_createItem"];
    /** 删除课程词项并重排 */
    delete: operations["CourseController_deleteItem"];
    options?: never;
    head?: never;
    /** 编辑课程词项（释义/提示/移动到其他单元） */
    patch: operations["CourseController_updateItem"];
    trace?: never;
  };
  "/api/v1/catalog/courses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 学习者可见课程列表（只读 current release + 本人报名/主课程状态） */
    get: operations["CatalogController_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/courses/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 课程详情：当前 release、有序单元概要与本人报名/主课程状态；不可见返回 404 */
    get: operations["CatalogController_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/courses/{id}/enroll": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 加入已发布课程（幂等）；可选 makePrimary */
    post: operations["CatalogController_enroll"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/primary-course": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** 把已报名课程设为主课程（事务内原子切换；未报名返回 409） */
    put: operations["CatalogController_setPrimary"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/study/cards/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 当前用户主课程的学习卡摘要（幂等补齐 current release 双向卡后统计） */
    get: operations["StudyController_summary"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/study/cards": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 当前用户自己的学习卡状态列表（默认主课程，可按已报名课程过滤） */
    get: operations["StudyController_cards"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/study/exposures": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 记录当前用户某课程词项学习面首次展示（幂等；只允许已报名课程 current release 词项，不改 FSRS，不产生复习/XP） */
    post: operations["StudyController_expose"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/study/today": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 今日概览：主课程、预算、计划候选数（due/initial/new）、是否有 active 会话、是否无任务（只读） */
    get: operations["StudyController_today"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/study/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 创建或恢复当前用户唯一 active 会话（幂等；刷新/重复调用返回同一会话；无候选返回 noWork，不创建空会话） */
    post: operations["StudyController_createOrResume"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/study/sessions/active": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 读取当前用户 active 会话详情（会话头 + 按 position 有序计划项）；无 active 会话 → 404 */
    get: operations["StudyController_activeDetail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/study/sessions/{sessionId}/items/{itemId}/reveal": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 展示确认：把当前 cursor 所指的 pending 计划项标记为 shown（幂等；重复 reveal 返回已 shown 状态，不产生 ReviewEvent/不改 FSRS/不推进 cursor） */
    post: operations["StudyController_reveal"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/study/sessions/{sessionId}/reviews": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 评分提交：对当前 cursor 所指、已 reveal 的计划项提交四级评分；幂等键去重（同请求重放，不同请求 409 IDEMPOTENCY_CONFLICT），事务内原子结算 FSRS 与 cursor */
    post: operations["StudyController_submitReview"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/study/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 进度概览（只读）：主课程 current release 各单元解锁 + 首测完成 + 稳定派生状态，由事件与快照完全重建 */
    get: operations["StudyController_progress"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/imports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 导入批次列表（管理员共享；元数据，不含磁盘路径/存储键） */
    get: operations["ImportController_list"];
    put?: never;
    /** 管理员上传原始文件并创建导入批次（multipart；Idempotency-Key 幂等；本票不解析文件内容） */
    post: operations["ImportController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/imports/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 单个导入批次详情（管理员共享；元数据，不含磁盘路径/存储键） */
    get: operations["ImportController_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginDto: {
      /** @description 登录用户名 */
      username: string;
      /** @description 密码 */
      password: string;
    };
    ChangePasswordDto: {
      /** @description 当前密码（或一次性密码） */
      currentPassword: string;
      /** @description 新密码 */
      newPassword: string;
    };
    CreateUserDto: {
      /** @description 登录用户名（小写） */
      username: string;
      /** @description 显示名 */
      displayName: string;
      /** @description IANA 时区 */
      timezone: string;
      /** @description 每日时间预算（分钟） */
      dailyBudgetMinutes: number;
      /**
       * @default learner
       * @enum {string}
       */
      role: "learner" | "admin";
    };
    LexicalEntrySummaryDto: {
      /** @description 词条 ID */
      id: string;
      /** @description 规范展示拼写 */
      canonicalSpelling: string;
      /** @description 查询/去重用规范化拼写 */
      normalizedSpelling: string;
      /** @description 词性（可空） */
      partOfSpeech: string | null;
      /** @description 来源状态（当前权威来源类型） */
      sourceStatus: string;
      /** @description 课程词项引用次数；课程词项工单落地前恒为 0（预留 lexicalEntryId 查询边界） */
      referenceCount: number;
      /** @description 最近更新时间 */
      updatedAt: string;
    };
    PageInfoDto: {
      /** @description 下一页游标；无更多时 null */
      cursor: string | null;
      /** @description 是否还有更多 */
      hasMore: boolean;
    };
    LexicalEntryListResponseDto: {
      items: components["schemas"]["LexicalEntrySummaryDto"][];
      page: components["schemas"]["PageInfoDto"];
    };
    SenseDto: {
      /** @description 中文释义 */
      meaning: string;
      /** @description 例句 */
      example?: string;
    };
    CreateLexicalEntryDto: {
      /** @description 规范展示拼写（保留原样，不因小写无条件合并同形异义词） */
      canonicalSpelling: string;
      /**
       * @description 词性
       * @enum {string}
       */
      partOfSpeech?:
        | "noun"
        | "verb"
        | "adjective"
        | "adverb"
        | "pronoun"
        | "preposition"
        | "conjunction"
        | "interjection"
        | "determiner"
        | "article"
        | "numeral"
        | "particle"
        | "phrase"
        | "abbreviation"
        | "prefix"
        | "suffix";
      /** @description 发音标注 */
      pronunciation?: string;
      /** @description 结构化释义 */
      senses?: components["schemas"]["SenseDto"][];
      /** @description 来源说明（不进入审计摘要） */
      sourceNote?: string;
      /**
       * @description 确认允许创建同形异义词条（重复候选提示后）
       * @default false
       */
      confirmDuplicate: boolean;
    };
    ProvenanceDto: {
      /** @description 来源类型 */
      sourceType: string;
      /** @description 来源说明 */
      sourceNote: string | null;
      /** @description 来源内容哈希 */
      contentHash: string;
      /** @description 创建者用户名 */
      createdByUsername: string | null;
      /** @description 来源记录时间 */
      createdAt: string;
    };
    AuditSummaryDto: {
      /** @description 审计动作 */
      action: string;
      /** @description 发生时间 */
      createdAt: string;
    };
    LexicalEntryDetailDto: {
      id: string;
      canonicalSpelling: string;
      normalizedSpelling: string;
      partOfSpeech: string | null;
      pronunciation: string | null;
      /** @description 结构化释义 */
      senses: components["schemas"]["SenseDto"][];
      /** @description 词条状态 */
      status: string;
      /** @description 来源状态（当前权威来源类型） */
      sourceStatus: string;
      /** @description 课程词项引用次数（课程词项落地前恒为 0） */
      referenceCount: number;
      createdAt: string;
      updatedAt: string;
      provenance: components["schemas"]["ProvenanceDto"][];
      /** @description 最近 10 条针对该词条的审计操作 */
      recentOperations: components["schemas"]["AuditSummaryDto"][];
    };
    DuplicateCandidateDto: {
      id: string;
      canonicalSpelling: string;
      normalizedSpelling: string;
    };
    DuplicateWarningErrorDto: {
      /** @description 错误码：DUPLICATE_WARNING 或 DUPLICATE_ENTRY */
      code: string;
      message: string;
      requestId: string;
      /** @description 重复候选词条 */
      duplicateCandidates: components["schemas"]["DuplicateCandidateDto"][];
      /** @description 是否可重试 */
      retryable: boolean;
    };
    DuplicateErrorEnvelopeDto: {
      error: components["schemas"]["DuplicateWarningErrorDto"];
    };
    CourseListItemDto: {
      id: string;
      /** @description 课程 slug（唯一） */
      slug: string;
      /** @description 当前标题（来自 active 草稿） */
      title: string;
      level: string;
      /** @description 当前描述（来自 active 草稿） */
      description: string | null;
      /** @description 课程可见性 */
      visibility: string;
      /** @description 课程状态 */
      status: string;
      /** @description active 草稿 ID */
      draftId: string | null;
      /** @description active 草稿版本 */
      draftVersion: number | null;
      /** @description 最近编辑时间（来自 active 草稿） */
      updatedAt: string;
    };
    CourseListResponseDto: {
      items: components["schemas"]["CourseListItemDto"][];
    };
    CreateCourseDto: {
      /** @description 课程 slug（唯一，小写字母/数字/连字符） */
      slug: string;
      /** @description 课程标题 */
      title: string;
      /**
       * @description 级别
       * @default a1
       * @enum {string}
       */
      level: "a1" | "a2" | "b1" | "b2" | "c1" | "c2";
      /** @description 课程描述 */
      description?: string;
    };
    CreateCourseResultDto: {
      courseId: string;
      draftId: string;
      /** @description 初始草稿版本 */
      draftVersion: number;
      slug: string;
      title: string;
      level: string;
    };
    DraftItemSummaryDto: {
      /** @description 全局词条 ID */
      id: string;
      /** @description 英语拼写 */
      canonicalSpelling: string;
      /** @description 规范化拼写 */
      normalizedSpelling: string;
      /** @description 词条来源状态 */
      sourceStatus: string;
    };
    ItemDto: {
      /** @description 稳定 course_item_id */
      id: string;
      /** @description 单元内 1 起始的位置 */
      position: number;
      /** @description 课程专属中文释义 */
      meaning: string;
      /** @description 可选提示 */
      hint: string | null;
      /** @description 人工内容 provenance：关联的管理员审计事件 ID */
      contentReviewReference: string;
      /** @description 引用的全局词条摘要 */
      lexicalEntry: components["schemas"]["DraftItemSummaryDto"];
      createdAt: string;
      updatedAt: string;
    };
    UnitDto: {
      /** @description 稳定 unit_id */
      id: string;
      /** @description 1 起始的位置 */
      position: number;
      title: string;
      description: string | null;
      /** @description 按 position 升序的课程词项 */
      items: components["schemas"]["ItemDto"][];
      createdAt: string;
      updatedAt: string;
    };
    CourseDraftDetailDto: {
      courseId: string;
      draftId: string;
      /** @description 课程 slug（唯一） */
      slug: string;
      title: string;
      level: string;
      description: string | null;
      /** @description 当前草稿版本 */
      version: number;
      status: string;
      /** @description 按 position 升序的单元大纲 */
      units: components["schemas"]["UnitDto"][];
    };
    ValidationIssueDto: {
      /** @description 稳定错误码 */
      code: string;
      /** @description 定位路径：course、unit.<unitId>、item.<itemId>.<field> */
      path: string;
      message: string;
      /**
       * @description error 阻断发布，warning 仅提示
       * @enum {string}
       */
      severity: "error" | "warning";
    };
    DiffSummaryDto: {
      /**
       * @description 首次发布或相对当前版本的差异
       * @enum {string}
       */
      kind: "initial" | "changed";
      addedUnits: number;
      removedUnits: number;
      addedItems: number;
      removedItems: number;
      changedItems: number;
      totalUnits: number;
      totalItems: number;
    };
    CourseValidationResultDto: {
      /** @description 被校验草稿的版本 */
      draftVersion: number;
      /** @description 是否存在阻断错误 */
      isPublishable: boolean;
      /** @description 阻断发布的问题 */
      blockingErrors: components["schemas"]["ValidationIssueDto"][];
      /** @description 提示但可发布的问题 */
      warnings: components["schemas"]["ValidationIssueDto"][];
      diffSummary: components["schemas"]["DiffSummaryDto"];
      /** @description 受影响学习者数量；第 4 阶段无报名数据时为 0 */
      affectedLearnerCount: number;
      /** @description 校验时刻（RFC 3339 UTC） */
      validatedAt: string;
      /** @description 草稿内容规范化序列化 SHA-256 */
      contentHash: string;
      /** @description 校验令牌：draftVersion.contentHash 前缀，发布须携带精确版本 */
      validationToken: string;
    };
    PublishReleaseDto: {
      /** @description 精确草稿版本（发布须重新确认） */
      draftVersion: number;
      /** @description 发布说明 */
      releaseNote?: string;
      /** @description 校验令牌（可选，须与草稿版本+内容哈希匹配） */
      validationToken?: string;
    };
    PublishReleaseResultDto: {
      releaseId: string;
      /** @description 每门课程单调递增的版本号 */
      releaseNumber: number;
      /** @description 发布快照内容哈希 */
      contentHash: string;
      /** @description 发布后成为当前版本指针 */
      currentReleaseId: string;
      createdAt: string;
    };
    DraftVersionConflictErrorDto: {
      /** @description 错误码：DRAFT_VERSION_CONFLICT */
      code: string;
      message: string;
      requestId: string;
      /** @description 服务端当前草稿版本 */
      currentDraftVersion: number;
      /** @description 是否可重试 */
      retryable: boolean;
    };
    DraftVersionConflictEnvelopeDto: {
      error: components["schemas"]["DraftVersionConflictErrorDto"];
    };
    ReleaseListItemDto: {
      id: string;
      releaseNumber: number;
      title: string;
      level: string;
      description: string | null;
      /** @description 快照内容哈希 */
      contentHash: string;
      /** @description 来源草稿版本 */
      sourceDraftVersion: number;
      /** @description 发布说明 */
      releaseNote: string | null;
      /** @description 创建者用户名 */
      createdByUsername: string;
      createdAt: string;
      /** @description 是否为当前版本 */
      isCurrent: boolean;
    };
    ReleaseListResponseDto: {
      items: components["schemas"]["ReleaseListItemDto"][];
    };
    SetCurrentReleaseDto: {
      /** @description 指向的已有 release ID（必须属于同一课程） */
      releaseId: string;
    };
    UpdateCourseDraftDto: {
      /** @description 课程 slug（唯一，小写字母/数字/连字符） */
      slug?: string;
      /** @description 课程标题 */
      title?: string;
      /**
       * @description 级别
       * @enum {string}
       */
      level?: "a1" | "a2" | "b1" | "b2" | "c1" | "c2";
      /** @description 课程描述 */
      description?: string;
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    CreateUnitDto: {
      /** @description 单元标题 */
      title: string;
      /** @description 单元描述 */
      description?: string;
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    UpdateUnitDto: {
      /** @description 单元标题 */
      title?: string;
      /** @description 单元描述 */
      description?: string;
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    DeleteUnitDto: {
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    ReorderUnitsDto: {
      /** @description 完整单元 ID 顺序（无重复、无遗漏） */
      unitIds: string[];
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    ReorderItemsDto: {
      /** @description 所属草稿单元 ID */
      unitId: string;
      /** @description 该单元内完整词项 ID 顺序（无重复、无遗漏、无陌生 ID） */
      itemIds: string[];
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    CreateItemDto: {
      /** @description 所属草稿单元 ID */
      unitId: string;
      /** @description 引用的全局词条 ID */
      lexicalEntryId: string;
      /** @description 课程专属中文释义（必填） */
      meaning: string;
      /** @description 可选提示 */
      hint?: string;
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    UpdateItemDto: {
      /** @description 课程专属中文释义（必填） */
      meaning?: string;
      /** @description 可选提示 */
      hint?: string;
      /** @description 移动到其他草稿单元（追加到该单元末尾） */
      unitId?: string;
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    DeleteItemDto: {
      /** @description 期望的草稿版本（If-Match 的替代） */
      draftVersion?: number;
    };
    CatalogCourseSummaryDto: {
      courseId: string;
      title: string;
      level: string;
      description: string | null;
      /** @description 当前版本 release ID */
      releaseId: string;
      /** @description 当前版本号 */
      releaseNumber: number;
      /** @description 内容来源：published_release（只读发布快照） */
      contentSource: string;
      /** @description 学习进度：阶段 4 恒为 not_started */
      progressStatus: string;
      /** @description 当前用户是否已报名 */
      isEnrolled: boolean;
      /** @description 当前用户是否将此课程设为主课程 */
      isPrimary: boolean;
    };
    CatalogCourseListResponseDto: {
      items: components["schemas"]["CatalogCourseSummaryDto"][];
    };
    CatalogUnitSummaryDto: {
      /** @description 稳定 unit_id */
      unitId: string;
      /** @description 1 起始的位置 */
      position: number;
      title: string;
      description: string | null;
    };
    CatalogCourseDetailDto: {
      courseId: string;
      title: string;
      level: string;
      description: string | null;
      /** @description 当前版本 release ID */
      releaseId: string;
      /** @description 当前版本号 */
      releaseNumber: number;
      /** @description 内容来源：published_release（只读发布快照） */
      contentSource: string;
      /** @description 学习进度：阶段 4 恒为 not_started */
      progressStatus: string;
      /** @description 当前用户是否已报名 */
      isEnrolled: boolean;
      /** @description 当前用户是否将此课程设为主课程 */
      isPrimary: boolean;
      /** @description 按 position 升序的单元概要 */
      units: components["schemas"]["CatalogUnitSummaryDto"][];
    };
    EnrollCourseDto: {
      /**
       * @description 加入后是否设为主课程
       * @default false
       */
      makePrimary: boolean;
    };
    SetPrimaryCourseDto: {
      /** @description 要设为主课程的已报名课程 ID */
      courseId: string;
    };
    LearningCardSummaryCountsDto: {
      /** @description 卡总数 */
      total: number;
      /** @description new 状态卡数（待首测） */
      new: number;
      /** @description learning 状态卡数 */
      learning: number;
      /** @description review 状态卡数 */
      review: number;
      /** @description 英文→中文方向卡数 */
      enToZh: number;
      /** @description 中文→英文方向卡数 */
      zhToEn: number;
    };
    LearningCardSummaryDto: {
      /** @description 主课程 ID */
      courseId: string;
      /** @description 主课程当前版本 release ID */
      releaseId: string;
      /** @description 主课程当前版本号 */
      releaseNumber: number;
      /** @description 当前版本课程词项数 */
      itemCount: number;
      /** @description 学习卡计数（按方向/状态） */
      cards: components["schemas"]["LearningCardSummaryCountsDto"];
      /** @description 已记录学习展示的词项数（每词项至多一次） */
      exposedItemCount: number;
    };
    LearningCardListItemDto: {
      /** @description 学习卡 ID */
      cardId: string;
      /** @description 课程 ID */
      courseId: string;
      /** @description 查询时刻课程的 current release ID */
      releaseId: string;
      /** @description 稳定课程词项 ID */
      courseItemId: string;
      /**
       * @description 卡方向
       * @enum {string}
       */
      direction: "en_to_zh" | "zh_to_en";
      /**
       * @description 记忆状态
       * @enum {string}
       */
      state: "new" | "learning" | "review";
      /** @description FSRS 稳定性 */
      stability: number;
      /** @description FSRS 难度 */
      difficulty: number;
      /** @description 预计间隔天数 */
      scheduledDays: number;
      /** @description 距上次复习经过天数 */
      elapsedDays: number;
      /** @description 复习次数 */
      reps: number;
      /** @description 遗忘次数 */
      lapses: number;
      /** @description 上次复习时间（new 卡为 null） */
      lastReviewAt: string | null;
      /** @description 到期时间（new 卡为创建时刻，待首测） */
      dueAt: string;
      /** @description 调度器版本（阶段 5 工单 01 恒为 fsrs-v6） */
      schedulerVersion: string;
      /** @description 词项英文拼写（来自 current release 快照） */
      englishSpelling: string;
      /** @description 词项中文释义（来自 current release 快照） */
      meaning: string;
      /** @description 该词项是否已记录学习展示 */
      exposed: boolean;
    };
    LearningCardListDto: {
      /** @description 按单元/词项位置排序的学习卡状态 */
      items: components["schemas"]["LearningCardListItemDto"][];
    };
    CreateExposureDto: {
      /** @description 已发布课程词项的稳定 course_item_id（必须是已报名课程 current release 中的词项） */
      courseItemId: string;
    };
    LearningExposureDto: {
      /** @description 学习展示记录 ID */
      exposureId: string;
      /** @description 稳定课程词项 ID */
      courseItemId: string;
      /** @description 引用的全局词条 ID */
      lexicalEntryId: string;
      /** @description 课程 ID */
      courseId: string;
      /** @description 首次展示时该课程的 current release ID（首次事实不可变） */
      releaseId: string;
      /** @description 首次展示时间（重复提交返回原值） */
      firstExposedAt: string;
      /** @description 本次是否为幂等重放（false=首次写入，true=已存在） */
      alreadyExisted: boolean;
    };
    TodayCountsDto: {
      /** @description 到期复习卡数（state=review 且 due_at <= now） */
      dueCount: number;
      /** @description 首次复习卡数（state=learning） */
      initialCount: number;
      /** @description 新卡数（state=new，仅 first unit 内） */
      newCount: number;
    };
    TodayDto: {
      /** @description 主课程 ID */
      courseId: string;
      /** @description 主课程当前版本 release ID */
      releaseId: string;
      /** @description 主课程当前版本号 */
      releaseNumber: number;
      /** @description 用户每日预算（分钟） */
      dailyBudgetMinutes: number;
      /** @description 计划候选数 */
      counts: components["schemas"]["TodayCountsDto"];
      /** @description 当前是否存在可恢复的 active 会话 */
      hasActiveSession: boolean;
      /** @description true 表示本次查询下无任何候选卡（预算和卡计数为 0） */
      noWork: boolean;
    };
    StudySessionDto: {
      /** @description 会话 ID */
      sessionId: string;
      /** @description 课程 ID */
      courseId: string;
      /** @description 会话创建时冻结的 current release ID */
      releaseId: string;
      /** @description 主课程当前版本号 */
      releaseNumber: number;
      /**
       * @description 会话状态
       * @enum {string}
       */
      status: "active" | "completed" | "abandoned";
      /** @description 用户每日预算（分钟） */
      dailyBudgetMinutes: number;
      /** @description 计划规则版本 */
      planRuleVersion: string;
      /** @description 计划创建时间 */
      plannedAt: string;
      /** @description 会话开始时间 */
      startedAt: string;
      /** @description 计划项数（总预算截断后的实际项数） */
      itemCount: number;
      /** @description 当前 cursor（下一个待展示项的 position） */
      cursor: number;
    };
    StudySessionItemDto: {
      /** @description 计划项 ID */
      itemId: string;
      /** @description 会话内展示顺序位置 */
      position: number;
      /** @description 学习卡 ID */
      cardId: string;
      /** @description 稳定课程词项 ID */
      courseItemId: string;
      /** @description 课程 ID */
      courseId: string;
      /**
       * @description 计划项分类
       * @enum {string}
       */
      itemKind: "due_review" | "initial_review" | "new_learning";
      /**
       * @description 计划项状态
       * @enum {string}
       */
      state: "pending" | "shown" | "completed" | "skipped_by_server";
      /**
       * @description 该计划项复习方向
       * @enum {string}
       */
      direction: "en_to_zh" | "zh_to_en";
      /** @description 英文拼写（来自会话冻结 release 快照，绝不来自 current release） */
      englishSpelling: string;
      /** @description 中文释义（来自会话冻结 release 快照，绝不来自 current release） */
      meaning: string;
      /** @description 提示（可空；来自冻结 release 快照） */
      hint: string | null;
    };
    StudySessionDetailDto: {
      /** @description 会话头 */
      session: components["schemas"]["StudySessionDto"];
      /** @description 按 position 排序的计划项 */
      items: components["schemas"]["StudySessionItemDto"][];
    };
    RevealResultDto: {
      /** @description 计划项 ID */
      itemId: string;
      /** @description 计划项在会话内的 position */
      position: number;
      /** @description 计划项绑定的稳定课程词项 ID */
      courseItemId: string;
      /**
       * @description reveal 后的计划项状态（应为 shown；幂等重放仍返回 shown）
       * @enum {string}
       */
      state: "pending" | "shown" | "completed" | "skipped_by_server";
      /**
       * @description 计划项分类
       * @enum {string}
       */
      itemKind: "due_review" | "initial_review" | "new_learning";
      /** @description 本次是否为幂等重放（true 表示该项已处于 shown） */
      alreadyShown: boolean;
      /** @description 是否为 new_learning（需确认学习面实际展示） */
      isNewLearning: boolean;
    };
    SubmitReviewDto: {
      /** @description 会话计划项 ID（必须是当前 cursor 所指的 pending 项，且已 reveal） */
      sessionItemId: string;
      /** @description 该计划项绑定的学习卡 ID（必须等于 item.card_id） */
      cardId: string;
      /**
       * @description 四级评分
       * @enum {string}
       */
      rating: "again" | "hard" | "good" | "easy";
      /** @description 客户端为「同一评分意图」生成的唯一 ID；重试复用同一 ID 以保证幂等 */
      clientEventId: string;
    };
    ReviewMemorySummaryDto: {
      /** @description 评分后的记忆状态 */
      state: string;
      /** @description FSRS 稳定性 */
      stability: number;
      /** @description FSRS 难度 */
      difficulty: number;
      /** @description 预计间隔天数 */
      scheduledDays: number;
      /** @description 下一次到期时间（服务器权威） */
      dueAt: string;
      /** @description 状态版本（乐观并发计数） */
      stateVersion: number;
      /** @description 调度器版本 */
      schedulerVersion: string;
      /** @description 调度参数版本 */
      schedulerParametersVersion: string;
    };
    ReviewSessionItemStateDto: {
      /** @description 计划项 ID */
      itemId: string;
      /**
       * @description 计划项状态（评分后将推进到 completed）
       * @enum {string}
       */
      state: "pending" | "shown" | "completed" | "skipped_by_server";
    };
    ReviewUnlockUnitDto: {
      /** @description 单元 position */
      position: number;
      /** @description 本单元是否已解锁 */
      unlocked: boolean;
      /** @description 本单元课程词项总数（current release 快照） */
      requiredItemCount: number;
      /** @description 本单元已完成双向首测的词项数（含本次提交首测的投影） */
      initialCompletedItemCount: number;
    };
    ReviewUnlockStateDto: {
      /** @description 当前可学习（最高已解锁）的单元 position */
      highestUnlockedUnit: number;
      /** @description current release 各单元派生解锁状态（按 position 升序） */
      units: components["schemas"]["ReviewUnlockUnitDto"][];
    };
    ReviewNextItemDto: {
      /** @description 下一计划项 ID；会话完成时为空 */
      itemId: Record<string, never>;
      /** @description 下一计划项 position */
      position: Record<string, never>;
      /** @description 下一计划项绑定的稳定课程词项 ID（安全摘要，无答案内容） */
      courseItemId: Record<string, never>;
      /**
       * @description 下一计划项分类；会话完成时为 null
       * @enum {string}
       */
      itemKind: "due_review" | "initial_review" | "new_learning";
    };
    SubmitReviewResultDto: {
      /** @description 本次是否为幂等重放（true=已存在同幂等键事件的回放） */
      idempotentReplay: boolean;
      /** @description ReviewEvent ID */
      reviewEventId: string;
      /**
       * @description 接受的评分
       * @enum {string}
       */
      rating: "again" | "hard" | "good" | "easy";
      /** @description 本事件是否被记录为首测（该方向首次有效评分） */
      isInitialReview: boolean;
      /** @description FSRS 更新后的记忆摘要 */
      memorySummary: components["schemas"]["ReviewMemorySummaryDto"];
      /** @description 当前会话计划项状态 */
      sessionItem: components["schemas"]["ReviewSessionItemStateDto"];
      /** @description 新 cursor（下一个待展示项的 position；会话完成时为 null） */
      newCursor: Record<string, never>;
      /** @description 会话是否已完成 */
      sessionCompleted: boolean;
      /** @description 由当前事实派生的单元解锁状态 */
      unlock: components["schemas"]["ReviewUnlockStateDto"];
      /** @description 若有下一项，返回下一项安全摘要；无则留空 */
      next: components["schemas"]["ReviewNextItemDto"];
    };
    ProgressItemStateDto: {
      /** @description 稳定课程词项 ID */
      courseItemId: string;
      /**
       * @description 方向
       * @enum {string}
       */
      direction: "en_to_zh" | "zh_to_en";
      /** @description 该方向是否已完成首测 */
      initialReviewed: boolean;
      /** @description 最近一次有效评分后的间隔天数（new 卡为 0） */
      scheduledDays: number;
      /** @description 是否已稳定（两方向间隔都 >= 21） */
      stable: boolean;
      /** @description 卡状态 */
      state: string;
    };
    ProgressUnitDto: {
      /** @description 单元 position */
      position: number;
      /** @description 单元标题（current release 快照） */
      title: string;
      /** @description 本单元是否已解锁 */
      unlocked: boolean;
      /** @description 本单元课程词项总数 */
      itemCount: number;
      /** @description 本单元已完成双向首测的词项数 */
      initialCompletedItemCount: number;
      /** @description 本单元各方向卡的首测/稳定派生状态 */
      cards: components["schemas"]["ProgressItemStateDto"][];
    };
    ProgressDto: {
      /** @description 主课程 ID */
      courseId: string;
      /** @description 主课程当前版本 release ID */
      releaseId: string;
      /** @description 主课程当前版本号 */
      releaseNumber: number;
      /** @description 当前最高已解锁单元 position */
      highestUnlockedUnit: number;
      /** @description 按 position 升序的单元进度 */
      units: components["schemas"]["ProgressUnitDto"][];
    };
    ImportUploadBodyDto: {
      /**
       * Format: binary
       * @description 原始文件（txt/csv/json）
       */
      file: string;
      /** @description 来源声明（必填） */
      sourceDeclaration: string;
    };
    StoredFileMetaDto: {
      /** @description 不透明文件 ID */
      fileId: string;
      /** @description 原文件名（仅元数据，绝不参与路径构造） */
      originalFilename: string;
      /** @description 嗅探到的 MIME 类型 */
      sniffedMime: string;
      /** @description 字节大小 */
      byteSize: number;
      /** @description SHA-256（十六进制） */
      sha256Hex: string;
      /** @description 上传人用户 ID */
      uploadedBy: string;
      /** @description 保留用途（本票固定 original_import） */
      purpose: string;
      /** @description 文件状态 */
      status: string;
      /** @description 格式（txt/csv/json/xlsx） */
      format: string;
      /** @description 创建时间（RFC 3339 UTC） */
      createdAt: string;
    };
    ImportBatchDto: {
      /** @description 批次 ID */
      id: string;
      /** @description 批次关联的文件元数据（不含磁盘路径/存储键） */
      file: components["schemas"]["StoredFileMetaDto"];
      /** @description 批次格式 */
      format: string;
      /** @description 管理员来源声明 */
      sourceDeclaration: string;
      /** @description 批次状态（uploaded/validating/ready/committed/failed） */
      status: string;
      /** @description 乐观并发版本 */
      version: number;
      /** @description 上传人用户 ID */
      uploadedBy: string;
      /** @description 创建时间（RFC 3339 UTC） */
      createdAt: string;
      /** @description 更新时间（RFC 3339 UTC） */
      updatedAt?: string;
    };
    ImportErrorFieldDto: {
      /** @description 出错字段路径 */
      path: string;
      /** @description 错误码 */
      code: string;
    };
    ImportErrorDto: {
      /** @description 错误码 */
      code: string;
      /** @description 安全的用户文案 */
      message: string;
      /** @description 可关联的请求 ID（服务端日志） */
      requestId: string;
      /** @description 是否为可重试错误 */
      retryable: boolean;
      /** @description 字段级错误（可选） */
      fieldErrors?: components["schemas"]["ImportErrorFieldDto"][];
      /** @description 内容冲突时既有批次的 ID */
      existingBatchId?: string;
    };
    ImportErrorEnvelopeDto: {
      /** @description 错误信封 */
      error: components["schemas"]["ImportErrorDto"];
    };
    ImportBatchListDto: {
      /** @description 批次列表（按创建时间倒序） */
      items: components["schemas"]["ImportBatchDto"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_live: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_sessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_revokeSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminUsersController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminUsersController_create: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminUsersController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminUsersController_disable: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminUsersController_reset: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LexicalEntryController_list: {
    parameters: {
      query?: {
        /** @description 按规范化/展示拼写搜索 */
        q?: string;
        /** @description 键集分页游标（上次响应返回） */
        cursor?: string;
        /** @description 每页数量 */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LexicalEntryListResponseDto"];
        };
      };
    };
  };
  LexicalEntryController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateLexicalEntryDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LexicalEntryDetailDto"];
        };
      };
      /** @description 重复警告/完全相同冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DuplicateErrorEnvelopeDto"];
        };
      };
    };
  };
  LexicalEntryController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LexicalEntryDetailDto"];
        };
      };
    };
  };
  CourseController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseListResponseDto"];
        };
      };
    };
  };
  CourseController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCourseDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateCourseResultDto"];
        };
      };
      /** @description slug 已存在 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CourseController_getDraft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
    };
  };
  CourseController_updateDraft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCourseDraftDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_validate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseValidationResultDto"];
        };
      };
    };
  };
  CourseController_releases: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReleaseListResponseDto"];
        };
      };
    };
  };
  CourseController_publish: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PublishReleaseDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublishReleaseResultDto"];
        };
      };
      /** @description 草稿版本过期/幂等冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_setCurrentRelease: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetCurrentReleaseDto"];
      };
    };
    responses: {
      /** @description 更新后的 currentReleaseId */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 跨课程 release 拒绝 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CourseController_createUnit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        unitId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUnitDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_deleteUnit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        unitId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteUnitDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_updateUnit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        unitId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUnitDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_reorder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderUnitsDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_reorderItems: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderItemsDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_createItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateItemDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_deleteItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteItemDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CourseController_updateItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateItemDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDraftDetailDto"];
        };
      };
      /** @description 草稿版本冲突 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftVersionConflictEnvelopeDto"];
        };
      };
    };
  };
  CatalogController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogCourseListResponseDto"];
        };
      };
    };
  };
  CatalogController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogCourseDetailDto"];
        };
      };
    };
  };
  CatalogController_enroll: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EnrollCourseDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogCourseDetailDto"];
        };
      };
    };
  };
  CatalogController_setPrimary: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetPrimaryCourseDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogCourseDetailDto"];
        };
      };
    };
  };
  StudyController_summary: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LearningCardSummaryDto"];
        };
      };
    };
  };
  StudyController_cards: {
    parameters: {
      query?: {
        /** @description 按已报名课程过滤；省略时默认主课程。必须属于当前用户，否则 404 */
        courseId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LearningCardListDto"];
        };
      };
    };
  };
  StudyController_expose: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateExposureDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LearningExposureDto"];
        };
      };
    };
  };
  StudyController_today: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TodayDto"];
        };
      };
    };
  };
  StudyController_createOrResume: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StudySessionDto"];
        };
      };
    };
  };
  StudyController_activeDetail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StudySessionDetailDto"];
        };
      };
    };
  };
  StudyController_reveal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sessionId: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevealResultDto"];
        };
      };
    };
  };
  StudyController_submitReview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitReviewDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubmitReviewResultDto"];
        };
      };
    };
  };
  StudyController_progress: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgressDto"];
        };
      };
    };
  };
  ImportController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportBatchListDto"];
        };
      };
    };
  };
  ImportController_create: {
    parameters: {
      query?: never;
      header: {
        /** @description 本次上传意图的幂等键；重试必须复用同一键 */
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["ImportUploadBodyDto"];
      };
    };
    responses: {
      /** @description 幂等重放或内容去重返回既有批次 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportBatchDto"];
        };
      };
      /** @description 新批次创建成功 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportBatchDto"];
        };
      };
      /** @description malformed 或安全文件拒绝 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportErrorEnvelopeDto"];
        };
      };
      /** @description IDEMPOTENCY_CONFLICT / IDEMPOTENCY_IN_PROGRESS / IMPORT_CONTENT_CONFLICT */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportErrorEnvelopeDto"];
        };
      };
      /** @description 字段或领域校验失败 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportErrorEnvelopeDto"];
        };
      };
      /** @description 统一内部错误信封 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportErrorEnvelopeDto"];
        };
      };
    };
  };
  ImportController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportBatchDto"];
        };
      };
      /** @description 非法 UUID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportErrorEnvelopeDto"];
        };
      };
      /** @description 批次不存在 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportErrorEnvelopeDto"];
        };
      };
    };
  };
}
